---
apiVersion: v1
kind: Secret
metadata:
  namespace: rant-bot
  name: rant-bot-secrets
type: Opaque
stringData:
  databaseUrl: $DATABASE_URL
  discordToken: $DISCORD_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rant-bot-deployment
  namespace: rant-bot
  labels:
    app: rant-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rant-bot
  template:
    metadata:
      labels:
        app: rant-bot
    spec:
      containers:
      - name: rant-bot
        image: $IMAGE
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rant-bot-secrets
              key: databaseUrl
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: rant-bot-secrets
              key: discordToken
        - name: DISCORD_PREFIX
          value: $DISCORD_PREFIX
